#defines stages
stages:
  - test
  - deploy

#Frontend: yarn build
yarn:
  stage: test
  image: node
  before_script:
    - cd frontend
  script:
    - yarn
    - yarn build
  after_script:
    - cd ..
  only:
    - master

#Backend: gradle build
gradle:
  stage: test
  image: gradle:jdk11
  before_script:
    - cd backend
  script:
    - gradle build
  after_script:
    - cd ..
  only:
    - master

deploy:
  type: deploy
  stage: deploy
  image: node
  before_script:
    - apt-get update -y
    - apt-get install ruby-dev
    - gem install dpl
    - cd frontend
  script:
    - yarn
    - yarn build
    - dpl --provider=heroku --app=$HEROKU_APP_FRONTEND --api-key=$HEROKU_API_KEY
  after_script:
    - cd ..

deploy-api:
  type: deploy
  stage: deploy
  image: gradle:jdk11
  before_script:
    - apt-get update -y
    - apt-get install ruby-dev
    - gem install dpl
    - cd backend
  script:
    - gradle build
    - dpl --provider=heroku --app=$HEROKU_APP_BACKEND --api-key=$HEROKU_API_KEY
  after_script:
    - cd ..
