# Define stages
stages:
  - test
  - deploy

# Frontend yarn build & test
test-frontend:
  stage: test
  image: node
  before_script:
    - cd frontend
  script:
    - yarn
    - yarn build
  after_script:
    - cd ..

# Backend gradle build & test
test-backend:
  stage: test
  image: gradle:jdk11
  before_script:
    - cd backend
  script:
    - gradle build --no-daemon
  after_script:
    - cd ..

# Frontend deploy to firebase
deploy-frontend:
  stage: deploy
  image: node
  before_script:
    - cd frontend
    - npm install -g firebase-tools
  script:
    - firebase deploy --token $FIREBASE_TOKEN
  after_script:
    - cd ..
  only:
    - tags

# Backend deploy needs to be made manually!
