
#defines stages
stages:
  - frontend
  - backend

#Frontend: yarn build
yarn:
  stage: frontend
  image: node
  before_script:
    - cd frontend
  script:
    - yarn
    - yarn build
  after_script:
    - cd ..

#Backend: gradle build
gradle:
  stage: backend
  image: gradle:jdk11
  before_script:
    - cd backend
  script:
    - gradle build
  after_script:
    - cd ..