name: Build and Deploy to kbar.app

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'frontend/**'
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        run: |
          cd frontend
          yarn install --immutable --immutable-cache --check-cache
          yarn build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KALKULIERBAR_8EDA1 }}'
          projectId: kalkulierbar-8eda1
          entryPoint: ./frontend
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
