name: Build and Deploy to preview URL

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-and-preview:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd frontend
          yarn install --immutable --immutable-cache --check-cache
          yarn build

      - name: Deploy
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KALKULIERBAR_8EDA1 }}'
          projectId: kalkulierbar-8eda1
          entryPoint: ./frontend
          expires: 30d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
