name: Build and Deploy to gce.kbar.app

on:
  push:
    branches:
    - master
    - main
    paths-ignore:
    - 'frontend/**'
    - 'README.md'
  pull_request:
    branches:
    - master
    - backend-workflow

jobs:
  setup-build-publish-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cd backend && ./gradlew build

    - name: Copy
      run: echo 'gce.kbar.app ${{ secrets.GCE_SSH_FINGERPRINT }}' > /tmp/host_fingerprint
      run: echo '${{ secrets.GCE_RSA_KEY }}' > /tmp/id_rsa
      run: scp -i /tmp/id_rsa build/libs/kalkulierbar-backend-all.jar -o "UserKnownHostsFile /tmp/host_fingerprint" user@gce.kbar.app:kalkulierbar/fresh.jar

    - name: Activate
      run: scp -i /tmp/id_rsa build/libs/kalkulierbar-backend-all.jar -o "UserKnownHostsFile /tmp/host_fingerprint" user@gce.kbar.app 'mv kalkulierbar/fresh.jar kalkulierbar/kalkulierbar-backend-all.jar && sudo systemctl restart kalkulierbar'